name = "imageToolBox"
uuid = "308a64e0-2da8-4ffc-993f-c99ea7c8dc9b"
authors = ["Wenbo Li <wenboli2016@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
